### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by vietbio** [VIB-PSB/trapid#1]
Hallo,

the server TRAPID-02 has been down for several days. Could you say something about the status and planning?

Best wishes with many thanks for your sharing and maintaining the system,

Hieu

###

Dr. Xuan Hieu Cao
Abteilung für Forstgenetik und Forstpflanzenzüchtung
Georg-August-Universität Göttingen
Büsgenweg 2
37077 Göttingen

ORCID: 0000-0003-1230-4127

**Comment by fbucchini** [comment]
Hello,

Thanks for reporting the issue.  The outage is due to some recent IT infrastructure changes. I will update you as soon as this is resolved.

Cheers,
Francois

**Comment by fbucchini** [comment]
It should be fixed by now, so I am closing this issue. Let us know if you experience any further issue!

Cheers,
Francois
